apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rest
spec:
  type: {{ .Values.service.type}}
  ports:
  - name: rest
    port: {{ .Values.service.port}}
    targetPort: 8081
  selector:
    app: flink
    component: jobmanager